## global.R ##
enableBookmarking(store = "url")
library(shiny)
require(visNetwork)
library(shinyBS)
library(Rcpp)
library(dplyr)
library(plotly)
library(deSolve)
library(shinydashboard)
library(shinythemes)
library(shinyjs)
library(shinycssloaders)
library(flexdashboard)
require(visNetwork)
library(shinyWidgets)
library(shinyjqui)
library(bsplus)
library(sweetalertR)
library(shinyLP)