# 1) load all packages
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(shinyEffects)
library(visNetwork)
library(plotly)
library(deSolve)
library(shinyjs)
library(shinyjqui)
library(shinycssloaders)
library(shinyWidgets)
library(bsplus)
library(sweetalertR)
library(shinytoastr)
library(stringr)
library(purrr)
library(rintrojs)
library(shinyFeedback)
library(magrittr)
library(DT)

# 2) Load the template components
source("help.R")
source("header.R")
source("sidebar.R")
source("body.R")
source("dashboardControlbar.R")

# 3) Load server components and functions
source("notifications.R")
source("graph_notifications.R")
source("animations.R")
source("modals.R")
source("generate_dynamicFooter.R")
